---
- name: Destroy temporary stack
  amazon.aws.cloudformation:
    access_key: "{{ rockylinux_ami_builder_aws_access_key | default('') }}"
    secret_key: "{{ rockylinux_ami_builder_aws_secret_key | default('') }}"
    region: "{{ rockylinux_ami_builder_aws_region }}"
    stack_name: "{{ rockylinux_ami_builder_stack_name }}"
    state: "absent"
